USE master;
GO

IF EXISTS(select * from sys.databases where name='bkim1790_sajat')
	DROP DATABASE bkim1790_sajat

CREATE DATABASE bkim1790_sajat;
GO

USE bkim1790_sajat;
GO

CREATE TABLE Soforok(
 -- SfID INT PRIMARY KEY IDENTITY,
   SfID INT IDENTITY,
   CONSTRAINT PK_SfID PRIMARY KEY(SfID),

  SfNeve VARCHAR(28),
  SfFizetes REAL,
  )
  
  CREATE TABLE Autok(
  --AID INT PRIMARY KEY IDENTITY,
  AID INT IDENTITY,
  CONSTRAINT PK_AID PRIMARY KEY(AID),
  Tipus VARCHAR(28),
  )

  CREATE TABLE Vezeti(
  	SfID INT,
	AID INT,

  CONSTRAINT FK_SfID FOREIGN KEY(SfID) REFERENCES Soforok(SfID),
  CONSTRAINT FK_AID FOREIGN KEY(AID) REFERENCES Autok(AID),
  CONSTRAINT PK_Vezeti PRIMARY KEY(SfID, AID)
  )


  CREATE TABLE SzallitoCegek(
  --  SzID INT PRIMARY KEY IDENTITY,
   SzID INT IDENTITY,
   CONSTRAINT PK_SzID PRIMARY KEY(SzID),
   SzNev VARCHAR(28),
 )

CREATE TABLE Alkalmazott(
  	SfID INT,
	SzID INT,

  CONSTRAINT FK_SfIDAlk FOREIGN KEY(SfID) REFERENCES Soforok(SfID),
  CONSTRAINT FK_SzID FOREIGN KEY(SzID) REFERENCES SzallitoCegek(SzID),
  CONSTRAINT PK_Alkalmazott PRIMARY KEY(SfID, SzID)
  )

  
  CREATE TABLE Internetescegek(
  --IcID INT PRIMARY KEY IDENTITY,
    IcID INT IDENTITY,
    CONSTRAINT PK_IcID PRIMARY KEY(IcID),
    IcNeve VARCHAR(50),
)  


CREATE TABLE Kuldet(
	SzID INT,
    IcID INT,
	KuldDatum DATE,

  CONSTRAINT FK_IcID FOREIGN KEY(IcID) REFERENCES Internetescegek(IcID),
  CONSTRAINT FK_SzIDKuld FOREIGN KEY(SzID) REFERENCES SzallitoCegek(SzID),
  CONSTRAINT PK_Kuldet PRIMARY KEY(SzID,IcID)
  )

 CREATE TABLE Termekek(
  --TID INT PRIMARY KEY IDENTITY,
  TID INT IDENTITY,
  CONSTRAINT PK_TID PRIMARY KEY(TID),
  TAr REAL,
  )
  
CREATE TABLE Elad(
	IcID INT,
    TID INT,
	EladDatum DATE,

  CONSTRAINT FK_IcIDEl FOREIGN KEY(IcID) REFERENCES Internetescegek(IcID),
  CONSTRAINT FK_TID FOREIGN KEY(TID) REFERENCES Termekek(TID),
  CONSTRAINT PK_Elad PRIMARY KEY(IcID,TID)
  )

  CREATE TABLE Vevok(
     --VID INT PRIMARY KEY IDENTITY,
	 VID INT IDENTITY,
	 CONSTRAINT PK_VID PRIMARY KEY(VID),
	 Rendelesek VARCHAR(40),
 )

 CREATE TABLE Szallit(
	SfID INT,
    VID INT,

  CONSTRAINT FK_SfIdSzal FOREIGN KEY(SfID) REFERENCES Soforok(SfID),
  CONSTRAINT FK_VID FOREIGN KEY(VID) REFERENCES Vevok(VID),
  CONSTRAINT PK_Szallit PRIMARY KEY(SfID,VID)
  )

CREATE TABLE Vasarol(
	VID INT,
    TID INT,
	VasarolDatum DATE,

  CONSTRAINT FK_VIDEl FOREIGN KEY(VID) REFERENCES Vevok(VID),
  CONSTRAINT FK_TIDEl FOREIGN KEY(TID) REFERENCES Termekek(TID),
  CONSTRAINT PK_Vasarol PRIMARY KEY(TID,VID)
  )

