DROP TABLE IF EXISTS ReszVetel
DROP TABLE IF EXISTS Muveszek
DROP TABLE IF EXISTS Szinpadok
DROP TABLE IF EXISTS Stilusok
DROP TABLE IF EXISTS Jegyek
DROP TABLE IF EXISTS JegyTipusok



CREATE TABLE Szinpadok(
  SzID INT PRIMARY KEY IDENTITY,
  SZNev VARCHAR(28),
  Cim VARCHAR(28),
  )
  
  CREATE TABLE Stilusok(
  StilusID INT PRIMARY KEY IDENTITY,
  SNev VARCHAR(28),
  Leiras VARCHAR(100),
 )
  
  CREATE TABLE Muveszek(
  MID INT PRIMARY KEY IDENTITY,
  MNev VARCHAR(50),
  StilusID INT FOREIGN KEY REFERENCES Stilusok(StilusID),
  SzOrszag VARCHAR(50),
  AlakulasiEv INT,
  SzinpadID INT FOREIGN KEY REFERENCES Szinpadok(SZID),
  KoncertNap INT,
  KezdIdopont INT,
)  

 CREATE TABLE JegyTipusok(
  JTID INT PRIMARY KEY IDENTITY,
  JTNev VARCHAR(28),
  Ar REAL,
  )
  
   CREATE TABLE Jegyek(
     JegyKod INT PRIMARY KEY IDENTITY,
	 JTID INT FOREIGN KEY REFERENCES JegyTipusok(JTID),
	  VasarloEletkor INT,
  )
  
   CREATE TABLE ReszVetel(
  JegyKod INT FOREIGN KEY REFERENCES Jegyek(JegyKod),
  MID INT FOREIGN KEY REFERENCES Muveszek(MID),
  PRIMARY KEY(JegyKod,MID),
  )